NAME="Cameron Trainer"
COURSE1="First Year Seminar II"
COURSE2="Introduction to Scripting"
COURSE3="State and Local Government"
echo "My name is $NAME, I am enrolled in $COURSE1, $COURSE2, and $COURSE3." 
